{% set name = "moment" %}
{% set version = "2.21.0" %}
{% set sha256 = "7a5443ce70ad5807215e2bc8fdf620f4fcaeb24e78631b8166697001f46da886" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moment/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g moment
  requires:
    - nodejs
   

about:
  home: https://github.com/moment/moment
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Parse, validate, manipulate, and display dates in javascript.'
  description: |
    A lightweight JavaScript date library for parsing, validating, manipulating, and formatting dates.   
  doc_url: http://momentjs.com/docs/
  dev_url: https://github.com/moment/moment

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
