{% set name = "moment" %}
{% set version = "2.22.2" %}
{% set sha256 = "52c253ad0e8645d2e8ed61fb15d1067821d0bc7f211a7520f585521c1480177f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moment/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g moment
  requires:
    - nodejs
   

about:
  home: https://github.com/moment/moment
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Parse, validate, manipulate, and display dates in javascript.'
  description: |
    A lightweight JavaScript date library for parsing, validating, manipulating, and formatting dates.   
  doc_url: http://momentjs.com/docs/
  dev_url: https://github.com/moment/moment

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
